brew "ansible"
brew "beanstalk" # a queue for testing ActiveJob::Retry
brew "cabal-install" # Haskell!
brew "clojurescript"
brew "elasticsearch"
brew "elixir"
brew "fzf"
brew "ghc"
brew "git"
brew "gnupg"
brew "go"
brew "gpg-agent"
brew "gradle110"
brew "heroku-toolbelt"
brew "leiningen"
brew "lftp"
brew "mercurial"
brew "mongodb" # wah
brew "mysql"
brew "nvm"
brew "openssl"
brew "postgresql"
brew "python"
brew "rabbitmq"
brew "rbenv"
brew "rbenv-default-gems"
brew "reattach-to-user-namespace"
brew "redis"
brew "ruby-build"
brew "sbt"
brew "scala"
brew "sqlite"
brew "terminal-notifier"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "vim"
brew "watchman"
brew "z"

# Casks
brew "brew-cask"
cask "alfred"
cask "bartender"
cask "copy"
cask "dashlane"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "java"
cask "iterm2"
cask "skype"
cask "slack"
cask "totalspaces"
cask "vagrant"
cask "virtualbox"

