call plug#begin('~/.vim/plugged')

" Syntax
Plug 'tpope/vim-git'
Plug 'vim-ruby/vim-ruby'
Plug 'jelera/vim-javascript-syntax'
Plug 'moll/vim-node'
Plug 'pangloss/vim-javascript'
Plug 'othree/html5.vim'
Plug 'elixir-lang/vim-elixir'
Plug 'rust-lang/rust.vim'
" haml also does Sass and SCSS

Plug 'tpope/vim-haml'
Plug 'chrisbra/csv.vim'
Plug 'leshill/vim-json'
Plug 'tpope/vim-markdown'
Plug 'andersoncustodio/vim-tmux'
Plug '1995eaton/vim-better-css-completion'
Plug '1995eaton/vim-better-javascript-completion'
Plug 'mustache/vim-mustache-handlebars'
Plug 'tpope/vim-cucumber'
Plug 'mxw/vim-jsx'

" Colour
Plug 'flazz/vim-colorschemes'
Plug 'john2x/flatui.vim'
Plug 'chriskempson/vim-tomorrow-theme'
Plug 'bling/vim-airline'

" Actual Plugs
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-surround'
Plug 'kien/ctrlp.vim'
Plug 'SirVer/ultisnips'
Plug 'christoomey/vim-tmux-navigator'
Plug 'tpope/vim-rbenv'
Plug 'tpope/vim-eunuch'
Plug 'thoughtbot/vim-rspec'
Plug 'editorconfig/editorconfig-vim'
Plug 'jackfranklin/vim-markdown-writer'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-dispatch'
Plug 'xolox/vim-misc'
Plug 'ervandew/supertab'
Plug 'benmills/vimux'
Plug 'tpope/vim-projectionist'
Plug 'tpope/vim-fugitive'
Plug 'kana/vim-textobj-user'
Plug 'nelstrom/vim-textobj-rubyblock'
Plug 'mattn/emmet-vim'
Plug 'ahw/vim-pbcopy'
Plug 'wellle/tmux-complete.vim'
Plug 'tpope/vim-ragtag'
Plug 'tommcdo/vim-exchange'
Plug 'AndrewRadev/switch.vim'
Plug 'AndrewRadev/splitjoin.vim'
Plug 'tpope/vim-rails'
Plug 'wellle/targets.vim'
Plug 'chrisbra/NrrwRgn'

" Buffer Explorer
Plug 'jlanzarotta/bufexplorer'

call plug#end()

filetype plugin indent on


runtime macros/matchit.vim

" status bar
set laststatus=2                                                               " Always show a statusline
let g:airline_powerline_fonts = 1
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_section_warning = ''

let g:airline#extensions#tabline#enabled = 1

"make vim-rspec play nice with tslime
let g:rspec_command = 'call VimuxRunCommand("clear; rspec {spec}")'

" vim test config
let g:test#strategy = 'dispatch'

" assume the /g flag on :s substitutions to replace all matches in a line
set gdefault

set autoread

" fix slight delay after pressing ESC then O
" http://ksjoberg.com/vim-esckeys.html
" set noesckeys
set timeout timeoutlen=500 ttimeoutlen=100

set nofoldenable

set history=10000

set textwidth=90
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set autoindent

set ignorecase smartcase

set spelllang=en_gb
syntax spell toplevel

autocmd FileType markdown setlocal shiftwidth=4 softtabstop=4 tabstop=4 wrap linebreak nolist wrap lbr colorcolumn=0

" ruby syntax highlighting is slower with the newer engine
autocmd FileType ruby setlocal regexpengine=1

set laststatus=2

set linebreak

set incsearch
set hlsearch

set scrolloff=10

set nobackup
set nowritebackup
set noswapfile


set backspace=indent,eol,start

set wildmode=full
set wildmenu

let mapleader=","
noremap \ ,

set wildignore+=*.o,*.obj,.git,node_modules,_site,*.class,*.zip,*.aux

set number
" set relativenumber

" pretty colours
set background=light
colorscheme Tomorrow-Night-Eighties

set colorcolumn=90

set list listchars=tab:»·,trail:·

command! Q q

set splitbelow
set splitright

set tags=./.tags;

set lazyredraw

" ~~~ MAPPINGS BELOW ~~~

"gtfo ex mode
map Q <Nop>

" vim test
nmap <silent> <leader>n :TestNearest<CR>
nmap <silent> <leader>e :TestFile<CR>
nmap <silent> <leader>l :TestLast<CR>

map <leader>cf :CtrlPClearCache<cr>
nnoremap <leader>vs :vsplit $MYVIMRC<cr>
map <leader>gf :e Gemfile<cr>
nnoremap <leader>h <Esc>:call ToggleHardMode()<CR>
nnoremap <leader>mt :call MW_MakeTwitterReferenceLink()<CR>
nnoremap <leader>mfi :call MW_ConvertFencedToIndent()<CR>
nnoremap <leader>my :call MW_YamlFrontMatter()<CR>
nnoremap <leader>ml :call MW_MakeWordLink()<CR>
map <Leader>nf :e <C-R>=expand("%:p:h") . "/" <CR>
map <leader>sc :setlocal spell!<CR>

map <leader>t :CtrlP<cr>
map <leader>v :vsplit<CR>
nnoremap <leader>W :%s/\s\+$//<cr>:let @/=''<cr>
map <Leader>p :set paste<CR>o<esc>"*]p:set nopaste<cr>

" map saving and tabs to Control-"
map <C-s> <esc>:w<CR>
imap <C-s> <esc>:w<CR>

vnoremap . :norm.<CR>

let g:ctrlp_map = ''
let g:ctrlp_clear_cache_on_exit = 1

" Don't add the comment prefix when I hit enter or o/O on a comment line.
autocmd FileType * setlocal formatoptions-=r formatoptions-=o

let g:UltiSnipsExpandTrigger="<c-k>"
let g:UltiSnipsJumpForwardTrigger="<c-k>"
let g:UltiSnipsJumpBackwardTrigger="<s-c-j>"
let g:UltiSnipsSnippetDirectories=["UltiSnips"]

nnoremap <CR> :noh<CR><CR>

" http://robots.thoughtbot.com/faster-grepping-in-vim/
set grepprg=ag\ --nogroup\ --nocolor

" Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

" Prevent Vim from clobbering the scrollback buffer. See
" http://www.shallowsky.com/linux/noaltscreen.html
set t_ti= t_te=

" stolen from https://bitbucket.org/sjl/dotfiles/src/tip/vim/vimrc
" Keep search matches in the middle of the window.
nnoremap n nzzzv
nnoremap N Nzzzv

noremap H ^
noremap L $
vnoremap L g_

" Uppercase word mapping.
"
" This mapping allows you to press <c-u> in insert mode to convert the current
" word to uppercase.  It's handy when you're writing names of constants and
" don't want to use Capslock.
"
" To use it you type the name of the constant in lowercase.  While your
" cursor is at the end of the word, press <c-u> to uppercase it, and then
" continue happily on your way:
inoremap <C-u> <esc>mzgUiw`za

" Stolen from Max
" Use system clipboard
set clipboard=unnamed
