if which rbenv > /dev/null; then eval "$(rbenv init - zsh)"; fi

[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

if ! [ -f "${HOME}/.zshenv-shared-info" ]; then
  touch "${HOME}/.zshenv-shared-info"
  ssh-agent >> "${HOME}/.zshenv-shared-info"
  gpg-agent --daemon >> "${HOME}/.zshenv-shared-info"
fi

. "${HOME}/.zshenv-shared-info"

