if which rbenv > /dev/null; then eval "$(rbenv init - zsh)"; fi

[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

if [ -f "${HOME}/.zshenv-shared-info" ]; then
  . "${HOME}/.zshenv-shared-info" &> /dev/null
fi

FOUND_SSH_PIDS=`ps aux | awk '{ print $2,$11 }' | grep ssh-agent | awk '{ print $1 }'`
FOUND_GPG_PIDS=`ps aux | awk '{ print $2,$11 }' | grep gpg-agent | awk '{ print $1 }'`
USED_GPG_PID=`echo $GPG_AGENT_INFO | cut -d':' -f2`

kill_zshenv_shared() {
  echo "Detected outdated agent(s):"
  echo "SSH: file says $SSH_AGENT_PID, but $FOUND_SSH_PIDS is running."
  echo "GPG: file says $USED_GPG_PID, but $FOUND_GPG_PIDS is running."
  killall ssh-agent
  killall gpg-agent
  rm "${HOME}/.zshenv-shared-info"
}

if [ $FOUND_SSH_PIDS -a $SSH_AGENT_PID -a $FOUND_GPG_PIDS -a $USED_GPG_PID ]; then
  # If these exist but don't match, the running agents and file are out of sync.
  if [ $FOUND_SSH_PIDS != $SSH_AGENT_PID -o $FOUND_GPG_PIDS != $USED_GPG_PID ]; then
    kill_zshenv_shared
  fi
else
  # If some of these don't exist, either an agent isn't running, or nothing is in the file.
  kill_zshenv_shared
fi

if ! [ -f "${HOME}/.zshenv-shared-info" ]; then
  touch "${HOME}/.zshenv-shared-info"
  ssh-agent >> "${HOME}/.zshenv-shared-info"
  gpg-agent --daemon >> "${HOME}/.zshenv-shared-info"

  . "${HOME}/.zshenv-shared-info" &> /dev/null
fi


