zsh_dotfile_path=$(dirname $(readlink $HOME/.zshrc))
fpath=($zsh_dotfile_path/zsh/completion $fpath)

# get auto completes going
autoload -U compinit
compinit

# Glob-like autocomplete
setopt glob_complete
setopt no_case_glob

# zsh history
setopt append_history
setopt share_history
setopt hist_ignore_dups

# El Capitan does weird things to $PATH, so we have to re-init rbenv here
if which rbenv > /dev/null; then eval "$(rbenv init - zsh)"; fi

source $zsh_dotfile_path/aliases
source $zsh_dotfile_path/exports
source $zsh_dotfile_path/functions
source $zsh_dotfile_path/agnoster-theme
source $zsh_dotfile_path/secret

HISTFILE=$HOME/.zhistory
HISTSIZE=20000
SAVEHIST=20000
setopt HIST_IGNORE_SPACE
HOSTNAME="`hostname`"

# But still use emacs-style zsh bindings
bindkey -e

# this allows Vim to use C-s as a mapping
stty -ixon

# better cding
# http://robots.thoughtbot.com/cding-to-frequently-used-directories-in-zsh
setopt auto_cd
cdpath=($HOME/gc $HOME/personal)

# probably a bit unsafe but yolo
export PATH="./bin:$PATH"

# nice diffing
export PATH="/usr/local/share/git-core/contrib/diff-highlight:$PATH"

if which brew >/dev/null; then
  [ -f `brew --prefix`/etc/profile/z.sh ] && source `brew --prefix`/etc/profile.d/z.sh
fi

# Use fzf for shell things too
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="/Users/isaac/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
