autoload compinit
compinit -u

# Glob-like autocomplete
setopt glob_complete
setopt no_case_glob

# zsh history
setopt append_history
setopt share_history
setopt hist_ignore_dups

source "$HOME/.zsh/aliases"
source "$HOME/.zsh/exports"
source "$HOME/.zsh/functions"
source "$HOME/.zsh/agnoster-theme"
if [ -f "$HOME/.zsh/secret" ]; then
  source "$HOME/.zsh/secret"
fi

HISTFILE="$HOME/.zhistory"
HISTSIZE=20000
SAVEHIST=20000
setopt HIST_IGNORE_SPACE

# But still use emacs-style zsh bindings
bindkey -e

# this allows Vim to use C-s as a mapping
stty -ixon

# better cding
# http://robots.thoughtbot.com/cding-to-frequently-used-directories-in-zsh
setopt auto_cd
cdpath=($HOME/work $HOME/me)

# Load Fast Node Manager (and have it auto-install when it sees a
# `.node-version` file)
eval "$(fnm env --use-on-cd)"

# El Capitan does weird things to $PATH, so we have to re-init rbenv here
if which rbenv > /dev/null; then
  eval "$(rbenv init -)"
fi

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"
base16_materia

# Hook in to direnv
eval "$(direnv hook zsh)"

# Launch the GPG agent
gpgconf --launch gpg-agent
