fpath=(~/dotfiles/zsh/completion $fpath)

# get auto completes going
autoload -U compinit
compinit

setopt prompt_subst

# Glob-like autocomplete
setopt glob_complete
setopt no_case_glob

# zsh history
setopt append_history
setopt share_history
setopt hist_ignore_dups

source $HOME/dotfiles/zsh/aliases
source $HOME/dotfiles/zsh/functions
source $HOME/dotfiles/zsh/agnoster-theme
source $HOME/dotfiles/zsh/secret

PATH="/usr/local/share/npm/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:$PATH"
PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"

TZ="Europe/London"
HISTFILE=$HOME/.zhistory
HISTSIZE=20000
SAVEHIST=20000
setopt HIST_IGNORE_SPACE
HOSTNAME="`hostname`"
PAGER='less'

#LANGUAGE
LC_ALL='en_US.UTF-8'
# LC_CTYPE=C
# DISPLAY=:0

GIT_MERGE_AUTOEDIT=no
export GIT_MERGE_AUTOEDIT

export EDITOR='vim'

# But still use emacs-style zsh bindings
bindkey -e

if which rbenv > /dev/null; then eval "$(rbenv init - zsh)"; fi

# this allows Vim to use C-s as a mapping
stty -ixon

# better cding
# http://robots.thoughtbot.com/cding-to-frequently-used-directories-in-zsh
setopt auto_cd
cdpath=($HOME/git $HOME/Dropbox $HOME/git/fyp $HOME/Dropbox/Sites)

# NODE
export NVM_DIR="/Users/Isaac/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# this has to be done after rbenv is inited
export PATH="./.bundle/binstubs:$PATH"

# probably a bit unsafe but yolo
export PATH="./bin:$PATH"

# for elastic search
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.7.0_65.jdk/Contents/Home"

# for Android SDK
export PATH="/Users/Isaac/android-sdk/tools:/Users/Isaac/android-sdk/platform-tools:$PATH"
export ANDROID_HOME="/Users/Isaac/android-sdk"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

if which brew >/dev/null; then
  source `brew --prefix`/etc/profile.d/z.sh
fi
